[package]
name = "lamp100w"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7.5"
panic-halt = "1.0.0"
rp-pico = "0.9.0"
embedded-hal = "1.0.0"
defmt = "1"
defmt-rtt = "1"
defmt-serial = "0.10.0"
